### ISSUE TITLE
The build process wont stop

### ISSUE THREAD

**Issue by ganjarsetia** [mholt/caddy-embed#2]
On my machine the build take about 9 hour and still running, so I terminate it. Do you know why this is happen?

![image](https://github.com/mholt/caddy-embed/assets/3258090/edd3fe21-4d59-4697-8058-57c6614aab98)

I'm using Ubuntu 22.04.2 LTS, go version 1.20.6, xcaddy v0.3.4

Step to reproduce

1. Install xcaddy: `sudo apt install xcaddy`
2. Clone the repo: `git clone https://github.com/mholt/caddy-embed.git && cd caddy-embed`
3. Build Caddy with plugin: `xcaddy build --with github.com/mholt/caddy-embed=.`

I tried reinstall xcaddy with `go install github.com/caddyserver/xcaddy/cmd/xcaddy@latest` and the output still the same. Do you think is xcaddy bug?

**Comment by mholt** [comment]
You're likely hitting this bug in Go: https://github.com/golang/go/issues/53905

**Comment by mholt** [comment]
What if you try `xcaddy build master ...` i.e. use the latest Caddy commits?

**Comment by ganjarsetia** [comment]
@mholt thanks for you reply!

its working when I run `xcaddy build master --with github.com/mholt/caddy-embed=.`

![image](https://github.com/mholt/caddy-embed/assets/3258090/65fd1db1-be33-4fe7-a6ac-f75c9e81e896)

Thanks
